# Generated by Django 3.2.16 on 2023-01-05 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='owner',
            new_name='writer',
        ),
        migrations.AlterField(
            model_name='message',
            name='attached_pic',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(default='write your messages'),
        ),
    ]
