# Generated by Django 3.2.16 on 2022-12-31 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
        migrations.AddField(
            model_name='profile',
            name='ballance',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='code_melli',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='f_name',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='img',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='l_name',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='video',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
