# Generated by Django 3.2.16 on 2022-12-31 22:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_is_complete'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserIdentDocs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_melli', models.PositiveBigIntegerField(null=True)),
                ('img', models.ImageField(null=True, upload_to='')),
                ('video', models.FileField(null=True, upload_to='')),
                ('ballance', models.PositiveBigIntegerField(default=0)),
                ('is_complete', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
