# Generated by Django 3.2.16 on 2023-01-02 02:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_useridentdocs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useridentdocs',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ident_Docs', to=settings.AUTH_USER_MODEL),
        ),
    ]
