# Generated by Django 3.2.16 on 2023-01-02 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_useridentdocs_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='ballance',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='code_melli',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='img',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_complete',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='video',
        ),
    ]
