# Generated by Django 3.2.16 on 2023-01-07 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orders_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_type',
            field=models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL')], default=('SELL', 'SELL'), max_length=50),
        ),
    ]
